### ISSUE TITLE
Little info paper for attendees

### ISSUE THREAD

**Issue by HerrBertling** [CSSclasses/CSSclasses-Hamburg#10]
Sollten relevante Infos enthalten:
- Wifi & Passwort
- Lernmaterial-Link
- Sponsorenlogos (siehe #8 )
- Mini-CoC?

**Comment by jonicious** [comment]
_We decided to have all our issues in English so anyone can understand them._

Translation:

Should include the following information:
- Wifi & Passwort
- Link to learn materials
- Logos of sponsors (see #8 )
- Mini-CoC?

**Comment by LeonardKoch** [comment]
@fallera Did this for the last meetup.
