### ISSUE TITLE
Create graph of attendee fluctuation

### ISSUE THREAD

**Issue by HerrBertling** [CSSclasses/CSSclasses-Hamburg#15]
Um ein Gefühl für die Fluktuation der Teilnehmer vor dem Event zu bekommen (Absagen/Nachrücker/…), sollten wir die An- und Abmeldezahlen etc. visualisieren.

=> @jonicious

**Comment by jonicious** [comment]
_We decided to have all our issues in English so anyone can understand them._

Translation:

To get a better sense of the fluctuation of attendees before the event takes place, we should visualise this information. We had a peek of 70 people attending and 30 on the waiting list. Before the event, many people declined.

**Comment by jonicious** [comment]
Green line: Attendees
Red line: Waiting list

![Graph](http://screenshots.jonas.re/NcQv7VDUr8.png)

You can see the graph [here](https://infogr.am/228a43c8-7b90-4976-b886-f444f8ca0645).
