### ISSUE TITLE
Send out survey after event

### ISSUE THREAD

**Issue by HerrBertling** [CSSclasses/CSSclasses-Hamburg#17]
Fragen gerne hier in den Kommentaren sammeln.

Quick fix: Google Form.

**Comment by HerrBertling** [comment]
- Wie hat es dir gefallen? (1-10)
- Würdest du wieder teilnehmen? (1-10)
- Würdest du CSSClasses deinen Freunden empfehlen? (1-10)
- Was würdest du anders machen? (freie Anmerkung)

**Comment by jonicious** [comment]
_We decided to have all our issues in English so anyone can understand them._

Translation:

Let's discuss questions for the survey in this thread. 

@HerrBertling added the following questions:
- How did you like the event? (1-10)
- Would you attend again? (1-10)
- Would you recommend CSSclasses to your friends? (1-10)
- What would you do different? (optional comment)

**Comment by jonicious** [comment]
@HerrBertling: I would change the second and third question to something like "How likely is it that you will attend again?" and "How likely is it that you will recommend CSSclasses to your friends?" since these are no "yes/no" questions. What do you think?

**Comment by jonicious** [comment]
More questions:
- How many CSSclasses meetups (no matter where) did you attend before? If you’ve not been to a CSSclasses meetup before, you don’t need to fill out this form.
- What's your experience with CSS?
  - None
  - Just curious
  - Use it on at least one development project
  - Use it on at least one production / open source project
  - Use it most days in my day job for production/development projects
- How would you rate the level of the learning material? (1 (very poor) - 10 (very good))
- How would you rate the help of the coaches? (1 very poor) - 10 (very good))
- How would you rate the length of the event? (1 (too short) - 10 (too long); 5 would be good)
- How do you feel about becoming a coach?
  - I'd love to be a coach but I don't have enough knowledge
  - I'd love to be a coach but I think I am not good at coaching
  - I don't know what coaches do
  - I'd love to be a coach but don't know how I become one
  - I could imagine being a coach in the future
- More learning materials on the following topics would be good (you can select multiple options):
  - How to build a basic website layout
  - Animations
  - Flexbox
  - How to structure your CSS
  - Others:
- Any other comments or general feedback to the meetup?
- Can we share your comments?
  - Yes - feel free to use my comments publicly
  - No - please keep my comments private. I understand that the multiple-choice answers may be summarised publicly.

**Comment by fallera** [comment]
I really would like to know why people _didn't_ attend. Can we add a switch early in the form, to show only relevant questions to either group? Then add something like this:

Would you have attended if...
- we provided a notebook for you
- we provided child care at the venue
- other

**Comment by jonicious** [comment]
I'd like to know how people felt about our CoC.
- How much impact did the CoC have on that you felt safe and welcoming at the meetup? (1 - 10)
- How much impact did the CoC have on your choice to attended the meetup? (1 - 10)
- How comfortable did you feel during the event? (1 - 10)
- Did you notice any occurrences that violate the CoC (yes / no)

**Comment by jonicious** [comment]
I'd like to send out the survey this weekend so that attendees still have some fresh impressions from last weekend and we can get the best feedback. @CSSclasses/hamburg Please add your questions as soon as possible and discuss about the questions above.

**Comment by jonicious** [comment]
- Where did you hear about the meetup? (free comment)

**Comment by fallera** [comment]
Addition to the part about the CoC:
- I didn't notice you had a CoC

Don't forget our coaches will get this survey too. Addition to the question about coaching:
- I did coach at this event

And another for coaches only:

If you were a coach at this meetup:
- How likely is it that you will coach at CSSclasses again? (1-10)
- How would you rate the provided information about coaching? (1-10)
- How comfortable did you feel as a coach? (1-10)
- What can we do to improve the experience for the coaches?
