### ISSUE TITLE
Meetup event: Set a proper end date.

### ISSUE THREAD

**Issue by HerrBertling** [CSSclasses/CSSclasses-Hamburg#6]
Der Default sind ~3 Stunden, das war beim 1. CSSClasses Workshop leider verwirrend.

**Comment by jonicious** [comment]
_We decided to have all our issues in English so anyone can understand them._

Translation:

Default on meetups is 3 hours which led to confusion because we did not set an end time for the event. Some attendees thought the event would end at 12:30pm because it started at 9:30am.
