### ISSUE TITLE
Add sponsor logos on materials

### ISSUE THREAD

**Issue by HerrBertling** [CSSclasses/CSSclasses-Hamburg#8]
Z.B.
- Wegweiser
- Kleine Infozettel
- etc. pp.

**Comment by jonicious** [comment]
_We decided to have all our issues in English so anyone can understand them._

Translation:

For example:
- signpost
- little info papers
- ...

**Comment by fallera** [comment]
... but don't place the logos too prominently so people don't think the event is theirs. ;)

**Comment by fallera** [comment]
Added this to checklists
