### ISSUE TITLE
Checklist for consumption of food & drinks

### ISSUE THREAD

**Issue by HerrBertling** [CSSclasses/CSSclasses-Hamburg#9]
(auf Wunsch von @jonicious ebenfalls anzumerken: Mehr Cola mit richtigem Zucker! :wink:)
### Pizza
- 1 große Joey's Pizza pro 2,3 Personen => 45 Teilnehmer/2,3 = 19,565217391 => 20 Pizzen
- Salat: Nicht wie Pizza anteilig berechnen, sondern pro Person, die Salat möchte, auch einen Salat bestellen.

**Comment by jonicious** [comment]
_We decided to have all our issues in English so anyone can understand them._

Translation:

### Pizza
- 1 large Joey's Pizza per 2.3 persons => 45 attendees/2.3 = 19,565217391 => 20 pizzas
- salad: Don't use the same formula as for pizza - order one salad per person

### Drinks

**Comment by fallera** [comment]
Drinks: 
- 2 Liter per person, half lemonade, half water:
- for 60 expected attendees: 60 \* 2 = 120L => 60L water (half sparkling half still) + 60L lemonade (more coke than other flavours)
- at the first CSSclasses-HH event 45 attendees drank ~60L so there were some leftovers (warm weather)
- buy on commission so we pay only for what is used

**Comment by fallera** [comment]
Snacks:

Plan for a short trip to the supermarket to provide some snacks in the afternoon:
- Fruit like apples + bananas
- Cookies
- Salt Sticks
